# Generated by Django 4.2.4 on 2023-09-13 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
